[package]
name = "why_gen_gen"
version = "0.0.1"
edition = "2018"
authors = ["Why Developers <mimblewimble@lists.launchpad.net>"]
description = "Utility to automate the generation of Why's genesis block"
license = "Apache-2.0"
repository = "https://github.com/mimblewimble/why"
keywords = [ "crypto", "why", "mimblewimble" ]
readme = "README.md"

[[bin]]
name = "gen_gen"
path = "src/bin/gen_gen.rs"

[dependencies]
chrono = "0.4.4"
cuckoo_miner = "1.0.0"
curl = "0.4.19"
why_core = { path = "../../core" }
why_chain = { path = "../../chain" }
why_keychain = { path = "../../keychain" }
why_miner_plugin = "1.0.0"
why_store = { path = "../../store" }
grin_util = { path = "../../util" }
why_wallet = { path = "../../wallet" }
rpassword = "2.0.0"
serde_json = "1"

[patch.crates-io]
why_api = { path = "../../api" }
why_core = { path = "../../core" }
why_chain = { path = "../../chain" }
why_keychain = { path = "../../keychain" }
grin_util = { path = "../../util" }
why_wallet = { path = "../../wallet" }
